# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def AnalyzeResponseTone(self, response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ResponseAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzeResponseTone(response=response,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeResponseTone", args={
                "response": response,
            })
            return typing.cast(types.ResponseAnalysis, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAgentResponse(self, raw_response: str,tool_names: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractAgentResponse(raw_response=raw_response,tool_names=tool_names,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAgentResponse", args={
                "raw_response": raw_response,"tool_names": tool_names,
            })
            return typing.cast(types.AgentResponse, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractConversation(self, raw_events: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Conversation:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractConversation(raw_events=raw_events,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractConversation", args={
                "raw_events": raw_events,
            })
            return typing.cast(types.Conversation, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidateMessage(self, role: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConversationMessage:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidateMessage(role=role,content=content,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidateMessage", args={
                "role": role,"content": content,
            })
            return typing.cast(types.ConversationMessage, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeResponseTone(self, response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ResponseAnalysis, types.ResponseAnalysis]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeResponseTone", args={
            "response": response,
        })
        return baml_py.BamlSyncStream[stream_types.ResponseAnalysis, types.ResponseAnalysis](
          result,
          lambda x: typing.cast(stream_types.ResponseAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ResponseAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractAgentResponse(self, raw_response: str,tool_names: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AgentResponse, types.AgentResponse]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAgentResponse", args={
            "raw_response": raw_response,"tool_names": tool_names,
        })
        return baml_py.BamlSyncStream[stream_types.AgentResponse, types.AgentResponse](
          result,
          lambda x: typing.cast(stream_types.AgentResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AgentResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractConversation(self, raw_events: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Conversation, types.Conversation]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractConversation", args={
            "raw_events": raw_events,
        })
        return baml_py.BamlSyncStream[stream_types.Conversation, types.Conversation](
          result,
          lambda x: typing.cast(stream_types.Conversation, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Conversation, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateMessage(self, role: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ConversationMessage, types.ConversationMessage]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidateMessage", args={
            "role": role,"content": content,
        })
        return baml_py.BamlSyncStream[stream_types.ConversationMessage, types.ConversationMessage](
          result,
          lambda x: typing.cast(stream_types.ConversationMessage, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ConversationMessage, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeResponseTone(self, response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeResponseTone", args={
            "response": response,
        }, mode="request")
        return result
    def ExtractAgentResponse(self, raw_response: str,tool_names: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAgentResponse", args={
            "raw_response": raw_response,"tool_names": tool_names,
        }, mode="request")
        return result
    def ExtractConversation(self, raw_events: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractConversation", args={
            "raw_events": raw_events,
        }, mode="request")
        return result
    def ValidateMessage(self, role: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateMessage", args={
            "role": role,"content": content,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeResponseTone(self, response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeResponseTone", args={
            "response": response,
        }, mode="stream")
        return result
    def ExtractAgentResponse(self, raw_response: str,tool_names: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAgentResponse", args={
            "raw_response": raw_response,"tool_names": tool_names,
        }, mode="stream")
        return result
    def ExtractConversation(self, raw_events: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractConversation", args={
            "raw_events": raw_events,
        }, mode="stream")
        return result
    def ValidateMessage(self, role: str,content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateMessage", args={
            "role": role,"content": content,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))