# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.Conversation": types.Conversation,
    "stream_types.Conversation": stream_types.Conversation,

    "types.ConversationMessage": types.ConversationMessage,
    "stream_types.ConversationMessage": stream_types.ConversationMessage,

    "types.ResponseAnalysis": types.ResponseAnalysis,
    "stream_types.ResponseAnalysis": stream_types.ResponseAnalysis,


    "types.MessageRole": types.MessageRole,

}