# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class MessageRole(str, Enum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"

# #########################################################################
# Generated classes (4)
# #########################################################################

class AgentResponse(BaseModel):
    main_response: str
    tools_used: typing.Optional[typing.List[str]] = None
    confidence: typing.Optional[float] = None
    requires_followup: bool

class Conversation(BaseModel):
    messages: typing.List["ConversationMessage"]
    turn_count: int
    has_tool_calls: bool

class ConversationMessage(BaseModel):
    role: MessageRole
    content: str

class ResponseAnalysis(BaseModel):
    tone: str
    is_error_message: bool
    suggested_improvement: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
