# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeResponseTone(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ResponseAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeResponseTone", llm_response=llm_response, mode="request")
        return typing.cast(types.ResponseAnalysis, result)

    def ExtractAgentResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAgentResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.AgentResponse, result)

    def ExtractConversation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Conversation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractConversation", llm_response=llm_response, mode="request")
        return typing.cast(types.Conversation, result)

    def ValidateMessage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ConversationMessage:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateMessage", llm_response=llm_response, mode="request")
        return typing.cast(types.ConversationMessage, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeResponseTone(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ResponseAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeResponseTone", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ResponseAnalysis, result)

    def ExtractAgentResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AgentResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAgentResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AgentResponse, result)

    def ExtractConversation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Conversation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractConversation", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Conversation, result)

    def ValidateMessage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ConversationMessage:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateMessage", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ConversationMessage, result)

    